apiVersion: v1
kind: Service
metadata:
  name: eaze-referral-api
  namespace: eaze-referral
spec:
  selector:
    app: eaze-referral-api
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
