// Mirrors eaze-referral-service/app/services/identity.py's decode_user_id — keep both in sync.
//
// The banner link's user_id is generated by the Eaze app itself, so it's expected to be
// well-formed. This is here to read the id, not to police it — the backend still does its own
// decode at the API boundary, and that's the one that actually gates anything.
//
// Handles URL-safe base64 and missing padding because those are real shapes a URL-carried id
// takes, not because the input is distrusted.
export function decodeUserId(raw: string): string | null {
  if (!raw) return null;

  const normalized = raw.replace(/-/g, '+').replace(/_/g, '/');
  const padded = normalized + '='.repeat((4 - (normalized.length % 4)) % 4);

  try {
    const binary = atob(padded);
    return new TextDecoder().decode(Uint8Array.from(binary, (char) => char.charCodeAt(0)));
  } catch {
    return null;
  }
}
